name: LiquidHaskell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mstksg/setup-stack@v2
    - name: Install LH
      run:  stack install liquidhaskell
    - name: Run LH
      run: stack exec -- liquid -isrc/ src/Main.hs
   
